on: workflow_dispatch

jobs :
  checkout:
    runs-on: ubuntu-latest
    steps :
       - name: checkout
         uses: actions/checkout@v6.0.0
       - name: list-elem
         run: ls -a -l
       - name: print_done
         run: echo DONE
        